NB_LINES_PRINTED = 5

NB_DATA_VALUES = 100
NB_DATA_TYPES = 3  # Should be 3
RANDOM_SEED_DATA = 0  # Remove for tests

NB_NN_INPUTS = 2
NB_NN_HIDDEN_LAYER_NEURONS = 64
NB_NN_EPOCHS = 1_000
NB_NN_EPOCHS_STEP = 100

LOSS_FUNCTION_TYPE = "CategoricalCrossentropy"
OPTIMIZE_FUNCTION_TYPE = "SGD"
ACTIVATION_TYPES = ["ReLU", "Softmax"]

COMBINED_SOFTMAX_CROSSENTROPY = True

LEARNING_RATE = 1.0
