NB_LINES_PRINTED = 5

NB_DATA_VALUES = 100
NB_DATA_TYPES = 3

LOSS_FUNCTION_TYPE = "CategoricalCrossentropy"
OPTIMIZE_FUNCTION_TYPE = "SGD"
ACTIVATION_TYPES = ["ReLU", "Softmax"]

COMBINED_SOFTMAX_CROSSENTROPY = False

LEARNING_RATE = 1.0
